version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress_site:/var/www/html/wordpress
      - adminer_v:/var/www/html/adminer
    networks:
      - net

  mariadb:
    container_name: mariadb
    image: mariadb
    restart: always
    build:
      context: mariadb
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - mysql_v:/var/lib/mysql
    networks:
      - net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
      interval: 5s
      timeout: 20s
      retries: 10
      start_period: 30s

  wordpress:
    container_name: wordpress
    image: wordpress
    restart: always
    build:
      context: wordpress
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - wordpress_site:/var/www/html/wordpress
    networks:
      - net

  adminer:
    container_name: adminer
    image: adminer
    build:
      context: bonus/adminer
      dockerfile: Dockerfile
    restart: always
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - adminer_v:/var/www/html/adminer
    ports:
      - "9090:9090"
    networks:
      - net

  redis:
    container_name: redis
    image: redis
    build:
      context: bonus/redis
      dockerfile: Dockerfile
    restart: always
    networks:
      - net

  ftp:
    container_name: ftp
    image: ftp
    build:
      context: bonus/ftp
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - wordpress
    volumes:
      - wordpress_site:/var/www/html/wordpress
    env_file:
      - .env
    ports:
      - "20:20"
      - "21:21"
      - "10090-10100:10090-10100"
    networks:
      - net

  portfolio:
    container_name: portfolio
    image: portfolio
    build:
      context: bonus/portfolio
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always

  portainer:
    container_name: portainer
    image: portainer
    build:
      context: bonus/portainer
      dockerfile: Dockerfile
    ports:
      - 9443:9443
    restart: always
    volumes:
      - prtainer_v:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - net


networks:
  net:
    driver: bridge

volumes:
  wordpress_site:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/ymarji/data/wp'
  mysql_v:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/ymarji/data/mysql'
  prtainer_v:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/ymarji/data/portainer'
  adminer_v:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/ymarji/data/adminer'