version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress_site:/var/www/html
    networks:
      - net

  mariadb:
    container_name: mariadb
    image: mariadb
    restart: always
    build:
      context: mariadb
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - wordpress_database:/var/lib/mysql
    networks:
      - net

  wordpress:
    container_name: wordpress
    image: wordpress
    restart: always
    build:
      context: wordpress
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - wordpress_site:/var/www/html
    networks:
      - net

networks:
  net:
    driver: bridge

# volumes:
#   nginx_data:
volumes:
  wordpress_site:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './data/wp'
  wordpress_database:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './data/mysql'