version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
      - "8888:8888"
    depends_on:
      - wordpress
    volumes:
      - ./data/wp:/var/www/html/wordpress
      - ./data/adminer:/var/www/html/adminer
    networks:
      - net

  mariadb:
    container_name: mariadb
    image: mariadb
    restart: always
    build:
      context: mariadb
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
      interval: 5s
      timeout: 20s
      retries: 10
      start_period: 30s

  wordpress:
    container_name: wordpress
    image: wordpress
    restart: always
    build:
      context: wordpress
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - ./data/wp:/var/www/html/wordpress
    networks:
      - net

  adminer:
    container_name: adminer
    image: adminer
    build:
      context: adminer
      dockerfile: Dockerfile
    restart: always
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - ./data/adminer:/var/www/html/adminer
    networks:
      - net

  redis:
    container_name: redis
    image: redis
    build:
      context: redis
      dockerfile: Dockerfile
    restart: always
    networks:
      - net

  ftp:
    container_name: ftp
    image: ftp
    build:
      context: ftp
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - wordpress
    volumes:
      - ./data/wp:/var/www/html/wordpress
    env_file:
      - .env
    ports:
      - "20:20"
      - "21:21"
      - "10090-10100:10090-10100"
    networks:
      - net

networks:
  net:
    driver: bridge

# volumes:
#   nginx_data:
# volumes:
#   wordpress_site:
#     driver: local
#     driver_opts:
#       type: 'none'
#       o: 'bind'
#       device: './data/wp'
#   wordpress_database:
#     driver: local
#     driver_opts:
#       type: 'none'
#       o: 'bind'
#       device: './data/mysql'