FROM debian:bullseye

RUN apt-get update
RUN apt-get -y install apt-transport-https lsb-release ca-certificates curl
RUN curl -sSLo /usr/share/keyrings/deb.sury.org-php.gpg https://packages.sury.org/php/apt.gpg
RUN sh -c 'echo "deb [signed-by=/usr/share/keyrings/deb.sury.org-php.gpg] https://packages.sury.org/php/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/php.list'
RUN apt-get update
RUN apt-get upgrade -y && \
  apt-get install -y \
  less \
  redis \
  wget \
  php7.4 \
  php7.4-cgi \
  php7.4-common \
  php7.4-fpm \
  php7.4-mysql \
  php7.4-bcmath \
  php7.4-curl \
  php7.4-gd \
  php7.4-mbstring \
  php7.4-xml \
  php7.4-xmlrpc \
  php7.4-soap \
  php7.4-intl \
  php7.4-zip \
  php7.4-memcached \
  php7.4-imagick \
  php7.4-opcache \
  php7.4-apcu
RUN apt install -y vim && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /var/run/
COPY ./conf/www.conf /etc/php/7.4/fpm/pool.d/www.conf

WORKDIR /tmp

RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
RUN php wp-cli.phar --info
RUN chmod +x wp-cli.phar
RUN mv wp-cli.phar /usr/local/bin/wp

COPY ./conf/entrypoint.sh .
RUN chmod +x entrypoint.sh

WORKDIR /var/www/html/wordpress
EXPOSE 9000 
ENTRYPOINT [ "/tmp/entrypoint.sh" ]
CMD ["php-fpm7.4", "-F"]
